-- Deprecated: duplicate of the hard-delete functions now included in
-- `chat_facts.sql`. The canonical implementations live in
-- `langmiddle/storage/supabase/chat_facts.sql`.
--
-- This file has been left as a pointer in the repo for a short period
-- for historical convenience. You can safely remove this file after
-- confirming `chat_facts.sql` contains the functions.
-- USAGE NOTES
-- ==========================================================
--
-- SOFT DELETE (default):
--   DELETE FROM facts WHERE id = 'fact-uuid' AND user_id = 'user-uuid'
--   - Removes fact from facts table
--   - History is preserved in fact_history table
--   - Can view deletion event with operation='DELETE'
--
-- HARD DELETE (permanent):
--   SELECT hard_delete_fact('fact-uuid', 'user-uuid')
--   - Removes fact from facts table
--   - Removes ALL embeddings for this fact
--   - Removes ALL history records for this fact
--   - Removes ALL access logs for this fact
--   - Cannot be recovered
--
-- BATCH HARD DELETE:
--   SELECT hard_delete_facts_batch(ARRAY['uuid1', 'uuid2', ...], 'user-uuid')
--   - Same as hard delete but for multiple facts at once
--   - Returns count of facts deleted
-- ==========================================================
